export const mockOpportunities = [
  {
    id: "1",
    title: "AI Compliance Assistant for SMB",
    industry: "AI",
    score: 91,
    summary: "Strong demand signal. Growing regulatory pressure. Low SMB-focused competition.",
    problem: "Small businesses struggle to understand and comply with new regulations.",
    customer: "SMBs with 10–100 employees",
    whyNow: "New EU regulations coming into effect in 2026.",
    mvp: "Company questionnaire → Regulatory database → AI assessment → Action plan.",
    risks: ["Legal liability", "Accuracy of AI recommendations"],
    recommendation: "BUILD",
  },
  {
    id: "2",
    title: "Freelancer Profitability Tool",
    industry: "SaaS",
    score: 87,
    summary: "Freelancers lack visibility into project profitability and time allocation.",
    problem: "Freelancers don't know which projects actually make them money.",
    customer: "Freelancers and small agencies",
    whyNow: "Rise of freelance economy, demand for financial clarity.",
    mvp: "Time tracking → Project cost analysis → Profitability dashboard.",
    risks: ["Market crowded with time trackers"],
    recommendation: "RESEARCH MORE",
  },
  {
    id: "3",
    title: "Automated Customer Research for Micro-SaaS",
    industry: "AI",
    score: 84,
    summary: "Micro-SaaS founders need customer insights but can't afford research teams.",
    problem: "Indie hackers launch products without talking to customers.",
    customer: "Indie hackers and micro-SaaS founders",
    whyNow: "AI makes automated research feasible at low cost.",
    mvp: "Reddit scraping → Pain extraction → Customer interview script generation.",
    risks: ["Data quality", "API limitations"],
    recommendation: "BUILD",
  },
  {
    id: "4",
    title: "Healthcare Admin Automation",
    industry: "Healthcare",
    score: 81,
    summary: "Clinics waste hours on manual paperwork and insurance processing.",
    problem: "Administrative burden reduces time for patient care.",
    customer: "Small clinics and private practices",
    whyNow: "Post-pandemic staffing shortages in healthcare.",
    mvp: "Intake forms → Document processing → Insurance pre-authorization assistant.",
    risks: ["Regulatory complexity", "Long sales cycles"],
    recommendation: "SKIP",
  },
  {
    id: "5",
    title: "SMB Procurement Automation",
    industry: "SaaS",
    score: 78,
    summary: "Small businesses overspend on software due to lack of procurement processes.",
    problem: "No centralized way for SMBs to manage software subscriptions.",
    customer: "SMBs with 20–200 employees",
    whyNow: "Software stack bloat is a growing pain point.",
    mvp: "Subscription discovery → Usage analysis → Cost optimization recommendations.",
    risks: ["Integration complexity"],
    recommendation: "RESEARCH MORE",
  },
];

export const industries = ["All", "SaaS", "AI", "Fintech", "Healthcare"];